language: go
go:
  - "1.10.x"
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go vet -v ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
