name: Test

on:
 - push
 - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
         - '1.17'
         - '1.18'
         - '1.19'
         - '1.20'
         - '1.21'
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge upstream
        if: github.event_name == 'pull_request'
        run: |
          if ! git config user.name > /dev/null; then
            git config user.name "John Doe"
          fi
          if ! git config user.email > /dev/null; then
            git config user.email "johndoe@localhost"
          fi
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream ${{ github.base_ref }}
          git pull --no-rebase --no-commit upstream ${{ github.base_ref }}
        shell: bash

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - run: go test -race -count=1 ./...
